spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:banking_account}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:true}

server:
  port: ${ACCOUNT_SERVICE_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
  metrics:
    export:
      prometheus:
        enabled: ${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:true}

app:
  account:
    min-balance: ${APP_ACCOUNT_MIN_BALANCE:0}
    max-balance: ${APP_ACCOUNT_MAX_BALANCE:1000000}
    default-currency: ${APP_ACCOUNT_DEFAULT_CURRENCY:USD}
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: ${JWT_EXPIRATION:86400000}

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: ${CIRCUIT_BREAKER_SLIDING_WINDOW_SIZE:10}
        failure-rate-threshold: ${CIRCUIT_BREAKER_FAILURE_RATE_THRESHOLD:50}
        wait-duration-in-open-state: ${CIRCUIT_BREAKER_WAIT_DURATION:10000}
        permitted-number-of-calls-in-half-open-state: 3
  ratelimiter:
    configs:
      default:
        limit-for-period: ${RATE_LIMITER_LIMIT_FOR_PERIOD:10}
        limit-refresh-period: ${RATE_LIMITER_LIMIT_REFRESH_PERIOD:1s}
        timeout-duration: 0
  retry:
    configs:
      default:
        max-attempts: ${RETRY_MAX_ATTEMPTS:3}
        wait-duration: ${RETRY_WAIT_DURATION:1000}
  bulkhead:
    configs:
      default:
        max-concurrent-calls: ${BULKHEAD_MAX_CONCURRENT_CALLS:5}
  timelimiter:
    configs:
      default:
        timeout-duration: ${TIME_LIMITER_TIMEOUT_DURATION:3s}
